version: '3'
services:
  mockopenai: # interface
    healthcheck:
      test: curl --fail http://127.0.0.1:8080/v1/models
      interval: 5s
      timeout: 5s
      retries: 5      
    environment:
      - GITHUB_PAT=${GITHUB_PAT}
      - GITHUB_REPO=${GITHUB_REPO}
    image: h4ckermike/mockopenai
    ports:
      -  "8080:5000"

  autogpt: #the beast
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: bash -c "poetry run autogpt --install-plugin-deps --skip-news --ai-name 'meta-autogpt'  --ai-role 'you will introspect autogpt and reveal its internals via reflection and comprehension'  --ai-goal 'Observe your behaviour'    --ai-goal 'Reflect over your outcomes'  --ai-goal 'Orient yourself to your knowledge'     --ai-goal 'Decide on your next step'     --ai-goal 'Act on your chosen next experiment' -y --continuous --continuous-limit 1 "

    # uncomment thse next 3 lines for debugging
    #entrypoint: /bin/bash
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
    environment:
      - GITHUB_PAT="${GITHUB_PAT}"
      - GITHUB_REPO="meta-introspector/call-auto-gpt"
      - OPENAI_API_KEY=your-openai-api-key
      - OPENAI_API_BASE=http://mockopenai:8080/v1
    image: h4ckermike/autogpt
    depends_on:
      - mockopenai
