name: AUTOGPT
on:
  workflow_dispatch :   #only run when requested
  issue_comment:
    types: [created]

jobs:
  printJob:
    permissions: write-all
      # repository:write
      
    name: Print event
    runs-on: ubuntu-latest
    #if: ${{ contains(fromJson('["nektos/act", "jmikedupont2", "Mysticmarks"]'), github.actor ) }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson (github) }}
          GITHUB_USER: ${{ github.event.comment.user.login }}
          GITHUB_REPO: ${{ github.repository }}
        run: |
          #echo TEST ${{ contains(fromJson('["nektos/act", "jmikedupont2", "Mysticmarks"]'), github.actor ) }}
          echo USER "$GITHUB_USER"
          echo USER "$GITHUB_REPO"
          echo ACTOR    "${{ github.actor }}"
          echo TRIGGER  "${{ github.triggering_actor }}"
          echo LOGIN    "${{ github.event.comment.user.login }}"

      - name: run gh workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson (github) }}
          GITHUB_USER: ${{ github.event.comment.user.login }}
          GITHUB_REPO: ${{ github.repository }}
        run: |
          echo TEST ${{ contains(fromJson('["nektos/act", "jmikedupont2", "Mysticmarks"]'), github.actor ) }}
          echo USER "$GITHUB_USER"
          echo USER "$GITHUB_REPO"
          echo ACTOR    "${{ github.actor }}"
          echo TRIGGER  "${{ github.triggering_actor }}"
          echo LOGIN    "${{ github.event.comment.user.login }}"
          #echo $GITHUB_CONTEXT | gh workflow run  -R jmikedupont2/ai-ticket run.yml \
          #   --ref docker-live-source-no-build || echo skip
          echo $GITHUB_CONTEXT | gh workflow run -R meta-introspector/ai-ticket run.yml  || echo done
          echo $GITHUB_CONTEXT | gh workflow run -R meta-introspector/call-auto-gpt run.yml  || echo done

