name: AUTOGPT
on: 
  issue_comment:                                                                                       
    types: [created]
  
jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson (github) }}
          GITHUB_USER: ${{ toJson (github.event.sender.login ) }}
          GITHUB_REPO: ${{ toJson ( github.repository )}}

        run: |
          echo CONTEXT "$GITHUB_CONTEXT"
          echo USER "$GITHUB_USER"
          # GET /repos/:owner/:repo/collaborators
          gh api -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "/repos/$GITHUB_REPO/collaborators/$GITHUB_USER"
 
          #github.event.sender.login
