name: AUTOGPT
on:
  workflow_dispatch :   #only run when requested
  issue_comment:                                                                                     
    types: [created]
  
jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson (github) }}
          GITHUB_USER: ${{ github.event.comment.user.login }}
          GITHUB_REPO: ${{ github.repository }}
        run: |
          
          echo USER "$GITHUB_USER"
          echo USER "$GITHUB_REPO"
          echo ACTOR    "${{ github.actor }}"
          echo TRIGGER  "${{ github.triggering_actor }}"
          echo LOGIN    "${{ github.event.comment.user.login }}"
  
      - name: Dump GitHub context
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson (github) }}
          GITHUB_USER: ${{ github.event.comment.user.login }}
          GITHUB_REPO: ${{ github.repository }}
          ACTION_URL: "/repos/${{ toJson ( github.repository )}}/collaborators/${{ toJson (github.event.sender.login ) }}"
        run: |
          echo 
          echo $ACTION_URL
          #gh api -H "Accept: application/vnd.github+json" \
          #  -H "X-GitHub-Api-Version: 2022-11-28" \
          #  $ACTION_URL
